FROM grafana/loki:latest

#USER root

#RUN apk add py3-pip \
#    && pip3 install cqlsh

ADD loki/etc/loki/local-config.yaml /etc/loki/local-config.yaml
#ADD loki/entrypoint.sh /entrypoint.sh

#USER loki

#ENTRYPOINT /entrypoint.sh
