version: "3.9"

services:
  ping-primary:
    build:
      context: .
      dockerfile: ping/Dockerfile
    image: ${IMAGE_BASE_NAME}-ping:latest
    container_name: ${BASE_NAME}-ping-primary
    labels:
      service.name: "ping-primary"
      service.group: "primary"
    environment:
      - "NAME=ping-primary"

  ping-secondary:
    build:
      context: .
      dockerfile: ping/Dockerfile
    image: ${IMAGE_BASE_NAME}-ping:latest
    container_name: ${BASE_NAME}-ping-secondary
    labels:
      service.name: "ping-secondary"
      service.group: "secondary"
    environment:
      - "NAME=ping-secondary"

  ping-tertiary:
    build:
      context: .
      dockerfile: ping/Dockerfile
    image: ${IMAGE_BASE_NAME}-ping:latest
    container_name: ${BASE_NAME}-ping-tertiary
    labels:
      service.name: "ping-tertiary"
      service.group: "secondary"
    environment:
      - "NAME=ping-tertiary"

networks:
  default:
    name: ${NETWORK}
